### ISSUE TITLE
KIRA JESTER

### ISSUE THREAD

**Issue by KiraaTheHustla** [saesrpg/donation-vehicle-shaders#351]
Vehicle ID
559

Wrap access
kira12345

Needs testing
yes

Thread for reward change
https://saesrpg.uk/topic/29755/kiraa-reward-change

Translations
None

Wrap image
![template_supra](https://user-images.githubusercontent.com/81694756/141370714-cfa02385-54ed-41ce-834b-c4d22e6e94c4.png)

**Comment by steven517** [comment]
You have the helper lines enabled, you should disable that layer

**Comment by KiraaTheHustla** [comment]
done! i edit it with new one without that lines helper

**Comment by tut98** [comment]
> Needs testing yes

The wrap can be tested by:
Using [Nanobob's wrap resource](https://github.com/NanoBob/saesrpg-wrap-testing) on your local server
Entering SF carshop's second floor on live server

**Comment by Liyones** [comment]
Hello, I've tested it for you @KiraaTheHustla looks cool but there is a problem with the front and roof and in behind, the problem is every time you add lines or some texture it won't just go well and it won't fit, you should move the lines little bit till it merges and fit with the whole texture in the car, Yeah it looks good in photoshop or the wrap but in-game it won't look the same so if you want to fix the lines you can pm me on discord and send me the PSD file and if you want to keep it no problem, it's up to you.

Here is the preview:
https://imgur.com/a/MhVSlaM

**Comment by KiraaTheHustla** [comment]
i test it ig looks good ty @Liyones 
mr @steven517 can we go for it ?

**Comment by KiraaTheHustla** [comment]
hi :D

**Comment by tut98** [comment]
On its way as `kira12345_4`

**Comment by steven517** [comment]
live
