### ISSUE TITLE
Jim's custom wrap request

### ISSUE THREAD

**Issue by Jim4222** [saesrpg/donation-vehicle-shaders#51]
Vehicle Name: Turismo
Vehicle ID: 451
Wrap access locked to usernames (leave blank if public): oximan42

https://imgur.com/a/XAE6grb

**Comment by tutgreco** [comment]
Before we add this, please upload a file that meets the criteria for image resolutions. Allowed image resolutions are: 256x256, 512x512, 1024x1024 (customs only)

**Comment by Jim4222** [comment]
is that the height and the width?

**Comment by tutgreco** [comment]
No, upscaling images results in quality loss while also taking up unnecessary space on our server. In your case please upscale to the nearest allowed resolution which would be 512x512. There's no point adding it as 1024x1024 as the quality does not improve at all, yet the file size improves 4 times instead of sticking to 512x512.

**Comment by Jim4222** [comment]
This one is 512x512

https://imgur.com/a/0k3IQkd

**Comment by Jim4222** [comment]
Can I see the wrap please?

**Comment by tutgreco** [comment]
Err, we prompt people to request review in the OP according to #1 , but yes. We'll edit this post with a preview.

**Comment by Jim4222** [comment]
Was there anything wrong?

**Comment by tutgreco** [comment]
Oh sorry the imgur didn't finish uploading. Yes, the bonnet (front hood) was totally misplaced as well as parts of the front bumper. Please see your older edits of the template so that you can see the problem by eye.
