### ISSUE TITLE
Custom shader for SGT

### ISSUE THREAD

**Issue by sparrow459** [saesrpg/donation-vehicle-shaders#9]
My donation SGT is at TT base can be shown ingame,
Vehicle locked to:kajs54,aymen000,kaseke123 (owner=kajs54)
Vehicle ID: 506
![sgt](https://user-images.githubusercontent.com/52857376/61175501-735bde00-a5a8-11e9-81bc-6a80ef9452bb.png)

**Comment by tutgreco** [comment]
The edges of the shadered parts needs to be orange, not white. This will otherwise show artifacts ingame.

Also, the "vehicle locked to" is unnecessary details. All we need to know is who are the owners of the wrap. Only owners of the wrap can use the wrap for their vehicles. Unless you meant that `kajs54,aymen000,kaseke123` are all to hold ownership of the wrap.

**Comment by sparrow459** [comment]
Im the owner of the wrap (kajs54)

**Comment by DemienD** [comment]
@sparrow459 @tutgreco 
Revised shader.

https://cdn.discordapp.com/attachments/599225234838650892/599616196505239576/sgt.png

**Comment by tutgreco** [comment]
I'll have this uploaded at my earliest convenience, likely next week.
